### ISSUE TITLE
Qemu's YAML descriptor is mal formed

### ISSUE THREAD

**Issue by maurorodrigues** [open-power-host-os/builds#1]
Current QEMU's descriptor is:

```
Package:
 name: 'QEMU'
 clone_url: 'https://github.com/open-power-host-os/qemu.git'
 branch: 'powerkvm-v3.1.1'
 commit_id: '7d4a58a'
 expects_source: "qemu-2200.0"
 specs:
  centos:
   '7.2': 
    spec: 'centOS/7.2/qemu.spec'
    build_files: 'centOS/7.2/SOURCES/*'
```

Which misses 'files' section, consider the diff below as reference of how it should look like:
```
Package:
 name: 'QEMU'
 clone_url: 'https://github.com/open-power-host-os/qemu.git'
 branch: 'powerkvm-v3.1.1'
 commit_id: '7d4a58a'
 expects_source: "qemu-2200.0"
- specs:
+ files:
  centos:
   '7.2': 
    spec: 'centOS/7.2/qemu.spec'
    build_files: 'centOS/7.2/SOURCES/*'
```
