### ISSUE TITLE
[RFC] Packages' YAML syntax to download source

### ISSUE THREAD

**Issue by snowcrshd** [open-power-host-os/builds#111]
As I was working on issue #97, some things came to my attention and I would like to discuss them here.

I'd like to add special syntax to our packages' YAML files in order to download the source files
necessary to build the RPM packages. I believe we should support the follow source files download use cases:

1. Clone from a Git repository (probably the vast majority of our use cases)
2. Clone from a Mercurial repository
3. Download a tarball file from a URL
4. A general command syntax to cover anything that does not fall in the previously mentioned use cases.

Below I list the proposed syntax for each case.

1. Clone from a Git repository (probably the vast majority of our use cases)
```
Package:
 name: 'servicelog'
 source:
   git: url='https://github.com/open-power-host-os/servicelog.git' branch='hostos-devel'  commit_id='7d33cd3'
   tar: src='servicelog' dest='servicelog.tar.gz'
  ...
```

2. Clone from a Mercurial repository
```
Package:
 name: 'python-six'
 source:
   hg: url='https://bitbucket.org/gutworth/six' branch='foo' changeset_id='7e95bb'
   tar: src='six' dest='python-six.tar.gz'
  ...
```

3. Download a tarball file from a URL
```
Package:
 name: 'python-foo'
 source:
   url: src='https://example.com/foo.tar.gz' dest='python-foo.tar.gz' md5sum='3858f62230ac3c915f300c664312c63f'
  ...
```

4. A general command syntax to cover anything that does not fall in the previously mentioned use cases.
```
Package:
 name: 'python-bar'
 source:
   commands:
     - curl http://example.com/bar.zip --output bar.zip
     - unzip bar.zip
     - cd  bar
     - ./configure
   tar: src='bar' dest='python-bar.tar.gz'
  ...
```

Obviously, we should avoid to use the last form (4) as much as possible. But it is best to get all our bases covered, I think.

What do you guys think of this syntax? Maybe there are other cases we should cover?

@maurorodrigues @olavphibm @fabianorosas @mopsfelder @gutoyr 

EDIT: On why I thought of this: Adding global HTTP proxy support requires that I pass command line options to GIT and Hg, to setup the proxy. Wget and Curl use HTTP_PROXY and HTTPS_PROXY environment variables, so we could get by always setting these variables when a global HTTP proxy was provided. It wouldn't work in the cases of Git and Hg, though.

**Comment by snowcrshd** [comment]
The `tar` field is used to create the tarball file that is given to the .spec files.
This would be used instead of the `expects_source` field (in the current syntax).

**Comment by maurorodrigues** [comment]
Thanks for bring this up. I'll not write a long answer about why or how our yaml is getting less adequate to shelter the use cases we have. Or how we need to specialized classes for each of those cases.

Getting straight to the point: I like what you're proposing here, and personally I only have 4 points I would like to discuss/add:

1.
> Clone from a Git repository (probably the vast majority of our use cases)
```
Package:
 name: 'servicelog'
 source:
   git: url='https://github.com/open-power-host-os/servicelog.git' branch='hostos-devel'  commit_id='7d33cd3'
   tar: src='servicelog' dest='servicelog.tar.gz'
  ...
```

I don't think we need to define the `tar: src='servicelog' dest='servicelog.tar.gz'` thing unless we plan to support some weird thing like clone multiple repositories and get them all together in a unique tar file. Not sure there is such case (people usually have submodule for such). Otherwise it's just something we can presume (yeah we can presume it right now, we should get rid of `expects_source` soon).

2. I think we need to 'normalize' the keys we're using:

> `git: url='https://github.com/open-power-host-os/servicelog.git' branch='hostos-devel'  commit_id='7d33cd3'`

and

> `hg: url='https://bitbucket.org/gutworth/six' branch='foo' changeset_id='7e95bb'`

Even though it can be harder for someone expecting to use the correct term for a given version control system I think it would be easier in general and something documented once for all kind of systems, something like url, branch and change_id for instance.

3. -1 for letting commands be specified. +1 for using pre defined hooks for such tasks as we discussed in our last meeting

4. Support for projects w/ multiple repositories (docker and kubernetes case).


Long story short: +1 for your suggestion and unless someone brings up an issue let's split it into tasks and start working.

**Comment by maurorodrigues** [comment]
Note: Just to make things clear: when I say I don't like item 4 and suggest to use hooks I don't want hooks as commands but a set of predefined (in code) actions that can be done and the user can trigger by adding them in the yaml file, so we keep our distance of custom commands that can be harmful or used to exploit things if someone distributes a malicious versions repository (of course we can't prevent this from happening if someone forks builds but we can prevent in this builds scripts).

**Comment by maurorodrigues** [comment]
Note 2: there are several sections that we can presume, putting a quick thought on kernel's yaml:
```
Package:
 name: 'kernel'
 clone_url: 'https://github.com/open-power-host-os/linux.git'
 branch: 'hostos-devel'
 commit_id: 'ce1fd2c'
 version:
   file: 'Makefile'
   regex: 'VERSION.*([\d.]+)\nPATCHLEVEL\s*=\s*(?P<patch>[\d.]*)\nSUBLEVEL\s*=\s*(?(patch)([\d.]*))'
 expects_source: "linux-source"
 files:
  centos:
   '7.2':
    spec: 'centOS/7.2/kernel.spec'
    rpmmacro: 'centOS/7.2/rpmmacro'
    build_files: 'centOS/7.2/SOURCES'
    build_dependencies:
     - 'gcc'
```
besides `expects_source`, we could also get rid of `rpmmacro`, `spec` and `build_files`. All those are things our code could guess and only be specified here as a convenience for user's experiments (like you want to try a different spec to add a patch but you don't want to commit)

**Comment by snowcrshd** [comment]
> I don't think we need to define the tar: src='servicelog' dest='servicelog.tar.gz' thing unless we plan to support some weird thing like clone multiple repositories and get them all together in a unique tar file. Not sure there is such case (people usually have submodule for such). Otherwise it's just something we can presume (yeah we can presume).

Agreed. Documenting this implicit behavior should be enough.

> Even though it can be harder for someone expecting to use the correct term for a given version control system I think it would be easier in general and something documented once for all kind of systems, something like url, branch and change_id for instance.

That makes sense. I think it will suffice to document the naming convention used.

> Support for projects w/ multiple repositories (docker and kubernetes case).

How could we go about that? Something like he example below?

```
sources:
  - git: url='...' branch='...' commit_id='...'
  - hg: url='...' branch='...' commit_id='...'
```

>  don't want hooks as commands but a set of predefined (in code) actions that can be done and the user can trigger by adding them in the yaml file, so we keep our distance of custom commands that can be harmful or used to exploit things if someone distributes a malicious versions repository

Makes sense. But I'm not sure how the syntax for this would look like.

Maybe:

```
sources:
  - git: url='...' branch='...' commit_id='...'
    init_submodules:
        - foo
        - bar
```

**Comment by maurorodrigues** [comment]
> How could we go about that? Something like the example below?
```
sources:
  - git: url='...' branch='...' commit_id='...'
  - hg: url='...' branch='...' commit_id='...'
```
Look like this a solution for the situation where we have both git and hg repositories for the same project, If I understand correct this is not exactly what I meant, if you take a look at https://github.com/open-power-host-os/versions/blob/master/docker/centOS/7.2/docker.spec#L104-L107 you will see that docker depends on multiple repositories (they probably split plugins or code that can be reused into a separated directory like a lib). So maybe it can be solved with some ugly thing like:
```
sources:
 - source1:
   - git: url='...' branch='...' commit_id='...'
 - source2:
   - git: url='...' branch='...' commit_id='...' 
 - source3:
   - hg: url='...' branch='...' commit_id='...'
```

**Comment by maurorodrigues** [comment]
> Makes sense. But I'm not sure how the syntax for this would look like.
Maybe:
```
sources:
  - git: url='...' branch='...' commit_id='...'
    init_submodules:
        - foo
        - bar
```

Yeah I don't know how it would look either and it could be appended to the yaml specification later imho. Just for the record I was thinking in something like:

```
sources
   - git: url='...' branch='...' commit_id='...' post_clone_hook="init" post_init_hook="..." and so on, we define some moments where we want to hook something, define what can be done on each moment and there it is.

**Comment by snowcrshd** [comment]
> Look like this a solution for the situation where we have both git and hg repositories for the same project, If I understand correct this is not exactly what I meant,

Actually, the idea is basically the same as  the one in your example.
Each item inside 'Package.sources' could represent a different project. I just used one 'hg' and one 'git' to illustrate the idea of dependencies that used different version control.

I just did not name each dependency.

**Comment by olavphibm** [comment]
I agree with most of your comments, there's just a small thing I'd like to add.
> I don't think we need to define the tar: src='servicelog' dest='servicelog.tar.gz' thing unless we plan to support some weird thing like clone multiple repositories and get them all together in a unique tar file. Not sure there is such case (people usually have submodule for such). Otherwise it's just something we can presume (yeah we can presume it right now, we should get rid of expects_source soon).

I've seen a few spec files that expect sources in bz2 or xz file format. The flexibility to allow those file formats would be nice in those cases, so our modifications in the spec files would be even smaller.

**Comment by snowcrshd** [comment]
> I've seen a few spec files that expect sources in bz2 or xz file format. The flexibility to allow those file formats would be nice in those cases, so our modifications in the spec files would be even smaller.

Good point. Maybe we could use a default for .tar.gz and support .bz2 and .xz if the user specifies this in the YAML?

@mopsfelder suggested something like on IRC:

```
git: url='...' commit_id='...' archive='abc.tar.bz2'
```

Or maybe:

```
git: url='...' commit_id='...' compress='bz2'
```

I'd like to specify the YAML syntax soon so I can create the tasks for this.
I think the longer we wait to add support for this, the bigger the technical debt we will have to deal with later.

**Comment by olavphibm** [comment]
I like this format: `git: url='...' commit_id='...' archive='abc.tar.bz2'`. Some packages expect a tar file with a different name (e.g. kernel->linux-source)

**Comment by olavphibm** [comment]
One more addition to the discussion. Github allows tar.gz files to be downloaded directly from any commit. Example: https://github.com/docker/docker/archive/85bc735b4a56223c84971839d819ff8dc494c181/docker.tar.gz
This could allow us to obtain tar files without even cloning the repo, but may make github a "special case" among other git repos.

**Comment by snowcrshd** [comment]
> One more addition to the discussion. Github allows tar.gz files to be downloaded directly from any commit

This could be useful. It might save us some time when building the packages.

**Comment by snowcrshd** [comment]
So, summing up what we have said so far, the package YAML definition would look like:

```
Package:
 name: 'foo'
 sources:
   - git: url='https://github.com/open-power-host-os/servicelog.git' branch='hostos-devel' commit_id='7d33cd3' archive='abc.tar.bz2'
   - hg: url='...' commit_id='...'
   - url: src='...' dest='...'
  ...
```

You can either specify `commit_id` or `branch`. If both are provided, `commit_id` is preferred.
